In [1]:
import tarfile

# Path to your .tar file
tar_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_dataset.tar'
extract_path = '/Users/jaeeponde/dsm_project/Yelp JSON/'

# Extract the tar file
with tarfile.open(tar_path, 'r') as tar:
    tar.extractall(path=extract_path)
    print("Extraction complete.")

Extraction complete.

In [2]:
import pandas as pd
import json

# Load the list of 100,000 user IDs
users_df = pd.read_csv("/Users/jaeeponde/dsm_project/data/user_core_100k.csv")
user_set = set(users_df['user_id'])

# Prepare for friend edges
friend_edges = set()

# Path to Yelp user JSON
input_path = "/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_user.json"

# Process each line (each user is one JSON object per line)
with open(input_path, 'r') as f:
    for line in f:
        user = json.loads(line)
        uid = user['user_id']
        
        # Only consider this user if they're in the selected 100k
        if uid in user_set:
            # Filter friends who are also in the selected users
            valid_friends = [fid for fid in user['friends'].split(', ') if fid in user_set]
            for fid in valid_friends:
                # Add a sorted tuple to prevent duplicate/undirected entries
                edge = tuple(sorted((uid, fid)))
                friend_edges.add(edge)

# Convert to DataFrame
friends_df = pd.DataFrame(list(friend_edges), columns=['user_id_1', 'user_id_2'])

# Save to CSV
friends_df.to_csv("/Users/jaeeponde/dsm_project/user_core_100k_friend_edges.csv", index=False)

print(f"✅ Saved {len(friends_df)} unique mutual friend edges.")

✅ Saved 518978 unique mutual friend edges.

In [3]:
import pandas as pd

# Load business data
business_df = pd.read_csv("/Users/jaeeponde/dsm_project/final_csv/list_of_restaurants.csv")

# Load filtered reviews (already tied to 100k users)
reviews_df = pd.read_csv("/Users/jaeeponde/dsm_project/data/sampled_reviews_100k_users.csv")

# Get the set of business IDs that have reviews
reviewed_business_ids = set(reviews_df['business_id'])

# Filter the business dataframe
filtered_businesses = business_df[business_df['business_id'].isin(reviewed_business_ids)]

# Save to new file
filtered_businesses.to_csv("/Users/jaeeponde/dsm_project/final_csv/list_of_restaurants_with_reviews.csv", index=False)

print(f"✅ Saved {len(filtered_businesses)} businesses that have reviews.")

✅ Saved 38636 businesses that have reviews.

In [1]:
import pandas as pd
import json

# Load the reviews dataset
tip_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_tip.json'

# This dataset is line-delimited JSON (each line is a JSON object)
tip = pd.read_json(tip_path, lines=True)

# Check the first few rows
tip

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
908910,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,Disappointed in one of your managers.,2021-09-11 19:18:57,0
908911,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,Great food and service.,2021-10-30 11:54:36,0
908912,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,Love their Cubans!!,2021-11-05 13:18:56,0
908913,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,Great pizza great price,2021-11-20 16:11:44,0
908914,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,Food is good value but a bit hot!,2021-12-07 22:30:00,0

In [2]:
tip.to_csv('tip.csv', index=False)

In [3]:
import pandas as pd
import json

# Load the reviews dataset
business_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_business.json'

# This dataset is line-delimited JSON (each line is a JSON object)
business = pd.read_json(business_path, lines=True)

# Check the first few rows
business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",None
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': '{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [4]:
business.to_csv('business.csv', index=False)

In [1]:
import json
import csv

# File paths
user_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_user.json'
csv_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_users.csv'

# Open JSON and CSV files
with open(user_path, 'r') as json_file, open(csv_path, 'w', newline='', encoding='utf-8') as csv_file:
    # Choose the fields you want to extract
    fieldnames = [
        'user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny',
        'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot',
        'compliment_more', 'compliment_profile', 'compliment_cute',
        'compliment_list', 'compliment_note', 'compliment_plain',
        'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos'
    ]

    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()

    for line in json_file:
        user = json.loads(line)
        # Flatten friends (list of user_ids) into count or string if needed
        user['friends'] = len(user.get('friends', '').split(', ')) if user.get('friends') else 0
        writer.writerow({field: user.get(field, None) for field in fieldnames})

In [2]:
import pandas as pd

csv_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_users.csv'
df = pd.read_csv(csv_path)

# Display basic info to confirm it loaded correctly
df

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,14995,267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...",4646,3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013",381,52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011",131,28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,NaN,27,1,...,1,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,2015-01-06 00:31:31,7,0,0,NaN,1,0,...,0,0,0,0,0,0,0,0,0,0
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,2016-06-14 07:20:52,0,0,0,NaN,1,0,...,0,0,0,0,0,0,0,0,0,0
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,2017-02-04 15:31:58,1,1,0,NaN,1,0,...,0,0,0,0,0,0,0,0,0,0
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,2011-01-14 00:29:08,0,0,0,NaN,1,0,...,0,0,0,0,0,0,0,0,0,0
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,2020-12-19 02:32:39,0,0,0,NaN,1,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
import json
import csv

# File paths
review_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_review.json'
csv_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_reviews.csv'

# Define fields to extract
fieldnames = ['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']

# Convert JSON lines to CSV
with open(review_path, 'r') as json_file, open(csv_path, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()

    for line in json_file:
        review = json.loads(line)
        # Write only the selected fields
        writer.writerow({field: review.get(field, None) for field in fieldnames})

In [1]:
import pandas as pd

csv_path = '/Users/jaeeponde/dsm_project/data/yelp_reviews.csv'
df = pd.read_csv(csv_path)

# Display basic info to confirm it loaded correctly
df

:

:

In [1]:
import json
import csv
import os

# Input path
review_path = '/Users/jaeeponde/dsm_project/Yelp JSON/yelp_academic_dataset_review.json'
output_dir = '/Users/jaeeponde/dsm_project/Yelp JSON/review_chunks'
os.makedirs(output_dir, exist_ok=True)

# Settings
chunk_size = 100000
fieldnames = ['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']

# Process
with open(review_path, 'r') as infile:
    chunk_num = 0
    line_count = 0
    outfile = open(os.path.join(output_dir, f'yelp_reviews_chunk_{chunk_num}.csv'), 'w', newline='', encoding='utf-8')
    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
    writer.writeheader()

    for line in infile:
        review = json.loads(line)
        writer.writerow({field: review.get(field, None) for field in fieldnames})
        line_count += 1

        if line_count % chunk_size == 0:
            outfile.close()
            chunk_num += 1
            outfile = open(os.path.join(output_dir, f'yelp_reviews_chunk_{chunk_num}.csv'), 'w', newline='', encoding='utf-8')
            writer = csv.DictWriter(outfile, fieldnames=fieldnames)
            writer.writeheader()

    outfile.close()

In [2]:
import pandas as pd

csv_path = '/Users/jaeeponde/dsm_project/Yelp JSON/review_chunks/yelp_reviews_chunk_0.csv'
df = pd.read_csv(csv_path)

# Display basic info to confirm it loaded correctly
df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
99995,pAEbIxvr6ebx2bHc1XvguA,SMH5CeiLvKx61lKwtLZ_PA,lV0k3BnslFRkuWD_kbKd0Q,4.0,0,0,0,Came here for lunch with a group. They were bu...,2018-05-30 22:28:56
99996,xH1AoE-4nf2ECGQJRjO4_g,2clTdtp-BjphxLjN83CpUA,G0xz3kyRhRi6oZl7KfR0pA,1.0,1,0,0,The equipment is so old and so felty! I just u...,2015-04-05 23:31:52
99997,GatIbXTz-WDru5emONUSIg,MRrN6DH3QGCFcDv5RENYVg,C4lZdhasjZVQyDlOiXY1sA,4.0,0,0,0,This is one of my favorite Mexican restaurants...,2016-06-04 00:59:15
99998,6NfkodAdhvI89xONXuBC3A,rnNQzeKJbvqVCsYsL10mkQ,dChRGpit9fM_kZK5pafNyA,2.0,0,0,0,Came here for brunch - had an omlette ($19 + t...,2018-06-11 12:45:08
99999,sJ1BMq7lkKgOWEFx3n6ZRw,_BcWyKQL16ndpBdggh2kNA,hMcgO98QaOFmQVTfCUeGzw,5.0,0,0,0,Came in for my 5-6 month prophy and saw Kara -...,2013-06-06 10:10:33